// Copyright 2026, DiamondForge
// SPDX-License-Identifier: Apache-2.0

package companion

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const clearCommand = "<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>"
const clearOutput = "<local-command-stdout></local-command-stdout>"
const caveat = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"

type fixtureRec struct {
	kind    string
	content any
	meta    bool
	extra   map[string]any
}

func userRec(content any) fixtureRec { return fixtureRec{kind: "user", content: content} }

func writeSession(t *testing.T, cwd string, recs ...fixtureRec) (*ClaudeAdapter, string, time.Time) {
	t.Helper()
	root := t.TempDir()
	dir := filepath.Join(root, ClaudeSlug(cwd))
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	start := time.Now()
	var lines []string
	for _, r := range recs {
		rec := map[string]any{
			"type": r.kind, "cwd": cwd, "sessionId": "s", "timestamp": start.UTC().Format(time.RFC3339Nano),
			"message": map[string]any{"role": "user", "content": r.content},
		}
		if r.meta {
			rec["isMeta"] = true
		}
		for k, v := range r.extra {
			rec[k] = v
		}
		b, err := json.Marshal(rec)
		if err != nil {
			t.Fatal(err)
		}
		lines = append(lines, string(b))
	}
	if err := os.WriteFile(filepath.Join(dir, "s.jsonl"), []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return MakeClaudeAdapter([]string{root}), cwd, start
}

func discoverOne(t *testing.T, recs ...fixtureRec) Candidate {
	t.Helper()
	a, cwd, start := writeSession(t, t.TempDir(), recs...)
	got := a.Discover(cwd, start)
	if len(got) != 1 {
		t.Fatalf("discover: %+v", got)
	}
	return got[0]
}

func TestClaudeTitleCommandThenPrompt(t *testing.T) {
	c := discoverOne(t,
		fixtureRec{kind: "user", content: caveat, meta: true},
		userRec(clearCommand),
		userRec(clearOutput),
		userRec("fix the tests"),
	)
	if c.Prompt != "fix the tests" || c.Command != "/clear" {
		t.Errorf("title: %+v", c)
	}
}

func TestClaudeTitleOnlyCommands(t *testing.T) {
	c := discoverOne(t, fixtureRec{kind: "user", content: caveat, meta: true}, userRec(clearCommand), userRec(clearOutput))
	if c.Prompt != "" || c.Command != "/clear" {
		t.Errorf("title: %+v", c)
	}
}

func TestClaudeTitleNothingYet(t *testing.T) {
	c := discoverOne(t, fixtureRec{kind: "user", content: caveat, meta: true})
	if c.Prompt != "" || c.Command != "" {
		t.Errorf("title: %+v", c)
	}
}

func TestClaudeTitleSkipsNonPrompts(t *testing.T) {
	image := []any{map[string]any{"type": "image", "source": map[string]any{"type": "base64"}}}
	c := discoverOne(t,
		userRec(image),
		userRec([]any{map[string]any{"type": "text", "text": "[Image #1]"}}),
		userRec("<system-reminder>Hook says hi</system-reminder>"),
		userRec("[Request interrupted by user]"),
		fixtureRec{kind: "user", content: "This session is being continued from a previous conversation", extra: map[string]any{"isCompactSummary": true}},
		userRec(clearCommand),
		userRec([]any{
			map[string]any{"type": "text", "text": "<system-reminder>ignored</system-reminder>"},
			map[string]any{"type": "text", "text": "  ajoute un\n  test   pour l'accentuation éàü 日本語  "},
		}),
	)
	if c.Prompt != "ajoute un test pour l'accentuation éàü 日本語" {
		t.Errorf("title: %+v", c)
	}
}

func TestClaudeTitleLongPrompt(t *testing.T) {
	c := discoverOne(t, userRec(strings.Repeat("日本語 ", 200)))
	if n := len([]rune(c.Prompt)); n != MaxPreviewRunes || !strings.HasSuffix(c.Prompt, "…") || strings.Contains(c.Prompt, "\n") {
		t.Errorf("title of %d runes: %q", n, c.Prompt)
	}
}

func TestClaudeTitleKeepsOwnAngleBrackets(t *testing.T) {
	c := discoverOne(t, userRec("<system-reminder>x</system-reminder>why does <div> break <Foo/> here?"))
	if c.Prompt != "why does <div> break <Foo/> here?" {
		t.Errorf("title: %q", c.Prompt)
	}
}

func TestCleanTitleTextNoMarkup(t *testing.T) {
	for _, tag := range titleMarkupTags {
		for _, in := range []string{"<" + tag + ">body</" + tag + "> after", "before <" + tag + "> after", "a </" + tag + "> b"} {
			if out := cleanTitleText(in); strings.Contains(out, "<"+tag) || strings.Contains(out, "</"+tag) {
				t.Errorf("%q gave %q", in, out)
			}
		}
	}
}

func TestCommandRecordIsNoTurn(t *testing.T) {
	s := MakeSession()
	a := MakeClaudeAdapter([]string{})
	at := time.Now().UnixMilli()
	for _, content := range []any{clearCommand, clearOutput, "<command-name>/compact</command-name>"} {
		a.parseUser(map[string]any{"message": map[string]any{"content": content}}, s, at)
	}
	a.parseUser(map[string]any{"message": map[string]any{"content": []any{map[string]any{"type": "text", "text": clearCommand}}}}, s, at)
	if s.nextTurn != 0 {
		t.Errorf("commands opened %d turns", s.nextTurn)
	}
	a.parseUser(map[string]any{"message": map[string]any{"content": "fix the tests"}}, s, at)
	if s.nextTurn != 1 {
		t.Errorf("a prompt opened %d turns", s.nextTurn)
	}
}

func TestCodexTitleUnchanged(t *testing.T) {
	cwd := t.TempDir()
	root := t.TempDir()
	dir := filepath.Join(root, "2026", "10", "07")
	os.MkdirAll(dir, 0o700)
	start := time.Now()
	meta, _ := json.Marshal(map[string]any{"type": "session_meta", "payload": map[string]any{"cwd": cwd, "id": "c1", "timestamp": start.UTC().Format(time.RFC3339Nano)}})
	msg, _ := json.Marshal(map[string]any{"type": "event_msg", "payload": map[string]any{"type": "user_message", "message": "  corrige   le test\nde <b>gras</b> "}})
	os.WriteFile(filepath.Join(dir, "rollout-2026-10-07T10-00-00-c1.jsonl"), []byte(string(meta)+"\n"+string(msg)+"\n"), 0o600)
	got := MakeCodexAdapter([]string{root}).Discover(cwd, start)
	if len(got) != 1 || got[0].Prompt != "corrige le test de <b>gras</b>" || got[0].Command != "" {
		t.Errorf("codex discover: %+v", got)
	}
}
